# Introduction {#intro}

*`r Sys.Date()`*

**Prologue**

The beginning of this project would need to be traced back to the middle of the European summer in 2020. Air was stiff, and the sun still shines bright. The corona virus is in the air, but that does not stop people going out. The usually perfect European summer consists of escaping to a Greek island, days out in the beaches of the Mediterranean, bottomless sangria, and not caring about what time of day it is. However, this year was different. Non-essential traveling is frowned upon. Eating out is not exactly an option. Staying at home is encouraged. Want to see friends? Zoom. Chat with family? WhatsApp. All the things we are used to is suddenly not available any longer. Well, welcome to the new norm.

**Start**

A lazy afternoon in the summer of 2020, students enrolled in the European Master in Official Statistics (EMOS) received an email promoting to take part in a new online activity - called the Eurostat Summer Coding Labs. Students taking the EMOS programs have the opportunity to participate in one of the coding lab projects. Around 6 people were enrolled in this specific coding lab called *Processing of Mobile Network Operator (MNO) Data for Spatial Statistics*. This specific lab is guided by Fabio Ricciato (Eurostat), aided by Mátyás Mészáros (Eurostat) and Jacopo Grazzini (Eurostat). The lab is divided into two teams: the R group and the Python group. The R group is made up of Giulia, Marco, Stefania, and Tony. The four students all comes from different countries with diverse experiences and backgrounds, but are determined to successfully complete this coding lab experience. 

**Motivation of this Project**

A good estimation of the population in a country is through the use of census data. During the census process, a count of each and every person present in the country is carried out. However, to carry out a census takes a lot of planning and is often associated with a high cost, thus it is common to carry out a census once every ten years. With the presence of high technological penetration in our everyday lives, estimating present population has never been easier. Assuming one mobile device is one person, we can then take the available data logged in each cell tower to approximate the present population located in the proximity of the tower. This is not the only real life application for this project. Other applications such as temporary population migration (e.g. holidays) or commuting habits of residents could also be explored. 

**This Book**

This book is divided into several chapters and within each chapter, the texts are further divided into sections and subsections. Each section is presented as a different page for easier navigation. For a complete understanding of our project, we suggest to first read about the ***Making a Toy World***, then ***Estimation Strategies***, and lastly ***Evaluation Methods***. We hope you will thoroughly enjoy this book and please let us know if you have any comments or suggestions. 