--- 
title: "Mobile Network Operator Data for Spatial Statistics - Eurostat Coding Labs 2020"
author: "Giulia Regazzoni, Marco Ramljak, Stefania Scrofani, Tony Hung"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "A showcase of our remote collaborative efforts from working on the MNO project"
---

# Cover

Joining far and wide in the heart of Europe, four master's students Skyped through the Eurostat Summer Coding Labs of the year 2020. Representing three universities from the Netherlands (UU), Italy (UniBg), and the Czech Republic (VŠE), while working collaboratively and have only seen each other through their laptop screens. The authors would like to present to you our book, a detailed collection of our work from the coding lab.

This book could be used in several ways. For a detailed overview of our project, a deep dive starting from the introduction is probably necessary. For a brief abstract, the executive summary could just be the case. This book is highly modular and adaptable to suit the reader's needs and curiosity.

We would like to sincerely thank Fabio Ricciato, Matyas Meszaros, and Jacopo Grazzini for their invaluable inputs and generous guidance throughout the coding lab experience.

This book is made using the `bookdown` package in R.

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
